# Generated by Django 3.2.7 on 2021-11-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
