# Generated by Django 3.2.7 on 2021-11-19 05:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_title', models.CharField(max_length=540)),
                ('resource_url', models.URLField()),
                ('author_name', models.CharField(max_length=250)),
                ('published_year', models.DateField()),
                ('description', models.TextField()),
                ('number_of_pages', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('page_number', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
