# Generated by Django 3.2.7 on 2021-11-17 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
