# Generated by Django 3.2.7 on 2021-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedcontent',
            name='default_heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='default_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedcontent',
            name='language_default',
            field=models.TextField(blank=True, null=True),
        ),
    ]
