# Generated by Django 3.2.7 on 2021-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationcontent',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conversationcontent',
            name='response_json',
            field=models.JSONField(null=True),
        ),
    ]
