# Generated by Django 3.2.7 on 2021-10-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_image/'),
        ),
    ]
