# Generated by Django 3.2.7 on 2021-11-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211111_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.gptapi'),
        ),
    ]
