# Generated by Django 3.2.7 on 2021-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_bot_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptapi',
            name='subtype',
            field=models.CharField(choices=[('none', 'None'), ('q&a', 'Q&A'), ('answers', 'Answers')], default='none', max_length=20),
        ),
    ]
